api_url: "https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/deepseek-v3/v1/chat/completions"
request_defaults:
  model: "deepseek-ai/DeepSeek-V3"
  max_tokens: 2048
  temperature: 0.7